import type { Inspection } from '@/lib/types'

export const primaryInspectionId = 'INSP-8832'

export const inspections: Inspection[] = [
  {
    id: 'INSP-8832',
    productId: 'PRD-1001',
    location: 'Retail Outlet, Sector 18, Noida',
    date: '02 Sep 2026',
    type: 'Routine Inspection',
    remarks: 'Routine market surveillance covering packaged food items on shelf.',
    inspector: 'Aarav Mehta',
    status: 'requires_review',
    aiScore: 83,
    createdAt: '2026-09-02T09:15:00Z',
    images: [
      {
        id: 'img-1',
        url: '/evidence/biscuits-front.png',
        filename: 'front-panel.jpg',
        fileSizeKb: 2140,
        panelType: 'Front',
        quality: 'good',
      },
      {
        id: 'img-2',
        url: '/evidence/biscuits-back.png',
        filename: 'back-panel.jpg',
        fileSizeKb: 1980,
        panelType: 'Back',
        quality: 'good',
      },
      {
        id: 'img-3',
        url: '/evidence/biscuits-side.png',
        filename: 'side-panel.jpg',
        fileSizeKb: 1420,
        panelType: 'Left Side',
        quality: 'low_light',
      },
      {
        id: 'img-4',
        url: '/evidence/biscuits-closeup.png',
        filename: 'declaration-closeup.jpg',
        fileSizeKb: 980,
        panelType: 'Close-up',
        quality: 'good',
      },
    ],
    declarations: [
      {
        id: 'decl-1',
        label: 'Product Name',
        value: 'ABC Premium Biscuits',
        confidence: 98,
        status: 'detected',
        region: { x: 18, y: 14, w: 64, h: 10 },
        evidenceImageId: 'img-1',
      },
      {
        id: 'decl-2',
        label: 'Manufacturer',
        value: 'ABC Foods Pvt. Ltd.',
        confidence: 96,
        status: 'detected',
        region: { x: 10, y: 68, w: 70, h: 10 },
        evidenceImageId: 'img-2',
      },
      {
        id: 'decl-3',
        label: 'Net Quantity',
        value: '500 g',
        confidence: 97,
        status: 'detected',
        region: { x: 62, y: 82, w: 24, h: 9 },
        evidenceImageId: 'img-1',
      },
      {
        id: 'decl-4',
        label: 'MRP',
        value: '\u20b9199',
        confidence: 91,
        status: 'review_required',
        region: { x: 10, y: 82, w: 22, h: 9 },
        evidenceImageId: 'img-1',
      },
      {
        id: 'decl-5',
        label: 'Date Information',
        value: 'MFD: 06/2026',
        confidence: 94,
        status: 'detected',
        region: { x: 14, y: 30, w: 40, h: 9 },
        evidenceImageId: 'img-2',
      },
      {
        id: 'decl-6',
        label: 'Consumer Care',
        value: 'Not confidently detected',
        confidence: 72,
        status: 'review_required',
        region: { x: 14, y: 46, w: 60, h: 10 },
        evidenceImageId: 'img-3',
      },
    ],
    findings: [
      {
        id: 'find-1',
        title: 'Consumer Care Information',
        status: 'pending',
        aiConfidence: 72,
        reason:
          'Consumer care information was not confidently detected in the submitted package images.',
        evidenceFilename: 'side-panel.jpg',
      },
    ],
    reportId: undefined,
  },
  {
    id: 'INSP-8801',
    productId: 'PRD-1002',
    location: 'Distribution Warehouse, Pune',
    date: '24 Aug 2026',
    type: 'Routine Inspection',
    inspector: 'Aarav Mehta',
    status: 'compliant',
    aiScore: 98,
    createdAt: '2026-08-24T11:00:00Z',
    images: [],
    declarations: [],
    findings: [],
    reportId: 'RPT-4401',
  },
  {
    id: 'INSP-8790',
    productId: 'PRD-1003',
    location: 'Retail Outlet, Andheri, Mumbai',
    date: '23 Aug 2026',
    type: 'Complaint-based Inspection',
    inspector: 'Priya Nair',
    status: 'requires_review',
    aiScore: 65,
    createdAt: '2026-08-23T15:30:00Z',
    images: [],
    declarations: [],
    findings: [],
    reportId: 'RPT-4388',
  },
  {
    id: 'INSP-8775',
    productId: 'PRD-1004',
    location: 'Retail Outlet, Connaught Place, Delhi',
    date: '22 Aug 2026',
    type: 'Follow-up Inspection',
    inspector: 'Priya Nair',
    status: 'potential_violation',
    aiScore: 42,
    createdAt: '2026-08-22T10:20:00Z',
    images: [],
    declarations: [],
    findings: [],
    reportId: 'RPT-4372',
  },
  {
    id: 'INSP-8760',
    productId: 'PRD-1005',
    location: 'Retail Outlet, Sector 18, Noida',
    date: '21 Aug 2026',
    type: 'Routine Inspection',
    inspector: 'Aarav Mehta',
    status: 'compliant',
    aiScore: 100,
    createdAt: '2026-08-21T09:45:00Z',
    images: [],
    declarations: [],
    findings: [],
    reportId: 'RPT-4360',
  },
  {
    id: 'INSP-8745',
    productId: 'PRD-1006',
    location: 'Retail Outlet, Koramangala, Bengaluru',
    date: '18 Aug 2026',
    type: 'Routine Inspection',
    inspector: 'Priya Nair',
    status: 'compliant',
    aiScore: 91,
    createdAt: '2026-08-18T13:10:00Z',
    images: [],
    declarations: [],
    findings: [],
    reportId: 'RPT-4340',
  },
]

export function getInspectionById(id: string) {
  return inspections.find((i) => i.id === id)
}
