import type { Product } from '@/lib/types'

export const products: Product[] = [
  {
    id: 'PRD-1001',
    brand: 'ABC Foods',
    name: 'ABC Premium Biscuits',
    category: 'Food',
    productType: 'Packaged Snacks',
    manufacturer: 'ABC Foods Pvt. Ltd.',
    packer: 'ABC Foods Pvt. Ltd.',
    importer: '-',
    countryOfOrigin: 'India',
    netQuantity: '500 g',
    mrp: '\u20b9199',
    batchNumber: 'BATCH-09A',
    mfgDate: '06/2026',
    consumerCare: '1800-XXX-XXXX / care@abcfoods.example',
    lastInspectionDate: '02 Sep 2026',
    inspectionCount: 12,
    latestScore: 83,
    status: 'requires_review',
    scoreHistory: [
      { date: 'Apr 2026', score: 96 },
      { date: 'May 2026', score: 91 },
      { date: 'Jun 2026', score: 88 },
      { date: 'Jul 2026', score: 94 },
      { date: 'Aug 2026', score: 79 },
      { date: 'Sep 2026', score: 83 },
    ],
  },
  {
    id: 'PRD-1002',
    brand: 'Golden Harvest',
    name: 'Organic Honey 500g',
    category: 'Food',
    manufacturer: 'Golden Harvest Apiaries',
    countryOfOrigin: 'India',
    netQuantity: '500 g',
    mrp: '\u20b9349',
    batchNumber: 'BATCH-22C',
    mfgDate: '01/2026',
    consumerCare: '1800-XXX-XXXX',
    lastInspectionDate: '24 Aug 2026',
    inspectionCount: 6,
    latestScore: 98,
    status: 'compliant',
    scoreHistory: [
      { date: 'Apr 2026', score: 92 },
      { date: 'May 2026', score: 94 },
      { date: 'Jun 2026', score: 97 },
      { date: 'Jul 2026', score: 95 },
      { date: 'Aug 2026', score: 98 },
    ],
  },
  {
    id: 'PRD-1003',
    brand: 'Mediterra',
    name: 'Premium Olive Oil 1L',
    category: 'Food',
    manufacturer: 'Mediterra Oils Ltd.',
    importer: 'Coastal Imports Pvt. Ltd.',
    countryOfOrigin: 'Spain',
    netQuantity: '1 L',
    mrp: '\u20b9899',
    batchNumber: 'BATCH-14B',
    mfgDate: '11/2025',
    consumerCare: 'support@mediterra.example',
    lastInspectionDate: '23 Aug 2026',
    inspectionCount: 4,
    latestScore: 65,
    status: 'requires_review',
    scoreHistory: [
      { date: 'May 2026', score: 88 },
      { date: 'Jun 2026', score: 74 },
      { date: 'Jul 2026', score: 70 },
      { date: 'Aug 2026', score: 65 },
    ],
  },
  {
    id: 'PRD-1004',
    brand: 'HomeMeasure',
    name: 'Digital Kitchen Scale',
    category: 'Household Products',
    manufacturer: 'HomeMeasure Electronics',
    importer: 'HomeMeasure Electronics',
    countryOfOrigin: 'China',
    netQuantity: '1 Unit',
    mrp: '\u20b91,299',
    batchNumber: 'BATCH-77X',
    mfgDate: '03/2026',
    consumerCare: '1800-XXX-XXXX',
    lastInspectionDate: '22 Aug 2026',
    inspectionCount: 3,
    latestScore: 42,
    status: 'potential_violation',
    scoreHistory: [
      { date: 'Jun 2026', score: 58 },
      { date: 'Jul 2026', score: 51 },
      { date: 'Aug 2026', score: 42 },
    ],
  },
  {
    id: 'PRD-1005',
    brand: 'Nature Bake',
    name: 'Whole Wheat Bread 800g',
    category: 'Food',
    manufacturer: 'Nature Bake Bakeries',
    countryOfOrigin: 'India',
    netQuantity: '800 g',
    mrp: '\u20b975',
    batchNumber: 'BATCH-05D',
    mfgDate: '08/2026',
    consumerCare: '1800-XXX-XXXX',
    lastInspectionDate: '21 Aug 2026',
    inspectionCount: 20,
    latestScore: 100,
    status: 'compliant',
    scoreHistory: [
      { date: 'Apr 2026', score: 99 },
      { date: 'May 2026', score: 100 },
      { date: 'Jun 2026', score: 100 },
      { date: 'Jul 2026', score: 98 },
      { date: 'Aug 2026', score: 100 },
    ],
  },
  {
    id: 'PRD-1006',
    brand: 'Velora',
    name: 'Hydrating Face Cream 100ml',
    category: 'Cosmetics',
    manufacturer: 'Velora Cosmetics Pvt. Ltd.',
    countryOfOrigin: 'India',
    netQuantity: '100 ml',
    mrp: '\u20b9549',
    batchNumber: 'BATCH-31F',
    mfgDate: '02/2026',
    consumerCare: 'care@velora.example',
    lastInspectionDate: '18 Aug 2026',
    inspectionCount: 5,
    latestScore: 91,
    status: 'compliant',
    scoreHistory: [
      { date: 'May 2026', score: 85 },
      { date: 'Jun 2026', score: 88 },
      { date: 'Jul 2026', score: 90 },
      { date: 'Aug 2026', score: 91 },
    ],
  },
]

export function getProductById(id: string) {
  return products.find((p) => p.id === id)
}
