'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { FileText, Search } from 'lucide-react'
import { AppShell } from '@/components/app-shell/app-shell'
import { PageHeader } from '@/components/page-header'
import { Input } from '@/components/ui/input'
import { Badge } from '@/components/ui/badge'
import { StatusBadge } from '@/components/status-badge'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useDataStore } from '@/lib/data-store'

export default function ReportsPage() {
  const { reports, inspections, products } = useDataStore()
  const [query, setQuery] = useState('')

  const rows = useMemo(() => {
    return reports
      .map((report) => {
        const inspection = inspections.find((i) => i.id === report.inspectionId)
        const product = inspection ? products.find((p) => p.id === inspection.productId) : undefined
        return { report, inspection, product }
      })
      .filter(({ report, product }) =>
        `${report.id} ${report.inspectionId} ${report.generatedBy} ${product?.name ?? ''} ${product?.brand ?? ''}`
          .toLowerCase()
          .includes(query.toLowerCase()),
      )
  }, [reports, inspections, products, query])

  return (
    <AppShell title="Reports">
      <PageHeader
        title="Reports"
        description="Generated compliance reports ready for filing, sharing, or export."
      />

      <div className="relative mb-4 max-w-sm">
        <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-secondary" />
        <Input
          placeholder="Search by report ID, inspection, or product"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          className="pl-9"
        />
      </div>

      <div className="overflow-hidden rounded-lg border border-border">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report</TableHead>
              <TableHead>Product</TableHead>
              <TableHead>Inspection</TableHead>
              <TableHead>Generated</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Result</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {rows.length === 0 && (
              <TableRow>
                <TableCell colSpan={7} className="py-10 text-center text-sm text-text-secondary">
                  <div className="flex flex-col items-center gap-2">
                    <FileText className="size-6 text-text-secondary/60" />
                    No reports match your search.
                  </div>
                </TableCell>
              </TableRow>
            )}
            {rows.map(({ report, inspection, product }) => (
              <TableRow key={report.id} className="hover:bg-muted/40">
                <TableCell>
                  <Link href={`/reports/${report.id}`} className="font-medium text-primary hover:underline">
                    {report.id}
                  </Link>
                </TableCell>
                <TableCell>
                  <div className="flex flex-col">
                    <span className="text-sm font-medium text-foreground">{product?.name ?? 'Unknown'}</span>
                    <span className="text-xs text-text-secondary">{product?.brand}</span>
                  </div>
                </TableCell>
                <TableCell>
                  <Link href={`/inspections/${report.inspectionId}`} className="text-sm text-primary hover:underline">
                    {report.inspectionId}
                  </Link>
                </TableCell>
                <TableCell className="text-sm text-text-secondary">{report.generatedDate}</TableCell>
                <TableCell className="text-sm text-text-secondary">{report.generatedBy}</TableCell>
                <TableCell>
                  <Badge variant="outline" className="capitalize">
                    {report.status}
                  </Badge>
                </TableCell>
                <TableCell>{inspection && <StatusBadge status={inspection.status} size="sm" />}</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </div>
    </AppShell>
  )
}
