from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    INSPECTOR = "INSPECTOR"


class InspectionStatus(str, Enum):
    DRAFT = "DRAFT"
    PROCESSING = "PROCESSING"
    ANALYSIS_COMPLETE = "ANALYSIS_COMPLETE"
    REQUIRES_REVIEW = "REQUIRES_REVIEW"
    COMPLIANT = "COMPLIANT"
    POTENTIAL_NON_COMPLIANCE = "POTENTIAL_NON_COMPLIANCE"
    COMPLETED = "COMPLETED"


class PanelType(str, Enum):
    FRONT = "FRONT"
    BACK = "BACK"
    LEFT = "LEFT"
    RIGHT = "RIGHT"
    TOP = "TOP"
    BOTTOM = "BOTTOM"
    CLOSE_UP = "CLOSE_UP"
    OTHER = "OTHER"


class DeclarationType(str, Enum):
    PRODUCT_NAME = "PRODUCT_NAME"
    MANUFACTURER = "MANUFACTURER"
    PACKER = "PACKER"
    IMPORTER = "IMPORTER"
    NET_QUANTITY = "NET_QUANTITY"
    MRP = "MRP"
    DATE_INFORMATION = "DATE_INFORMATION"
    CONSUMER_CARE = "CONSUMER_CARE"
    COUNTRY_OF_ORIGIN = "COUNTRY_OF_ORIGIN"
    OTHER = "OTHER"


class DeclarationStatus(str, Enum):
    DETECTED = "DETECTED"
    MISSING = "MISSING"
    REVIEW = "REVIEW"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class RuleSeverity(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ValidationType(str, Enum):
    PRESENCE = "PRESENCE"
    FORMAT = "FORMAT"
    READABILITY = "READABILITY"
    UNIT = "UNIT"
    DATE = "DATE"
    CONTACT = "CONTACT"
    FONT_SIZE = "FONT_SIZE"


class RuleResult(str, Enum):
    PASS = "PASS"
    REVIEW = "REVIEW"
    FAIL = "FAIL"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ViolationType(str, Enum):
    MISSING_DECLARATION = "MISSING_DECLARATION"
    READABILITY = "READABILITY"
    FORMAT = "FORMAT"
    VALUE_VALIDATION = "VALUE_VALIDATION"
    FONT_SIZE_ESTIMATE = "FONT_SIZE_ESTIMATE"
    MULTIPLE_VALUES = "MULTIPLE_VALUES"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"


class ViolationStatus(str, Enum):
    AI_DETECTED = "AI_DETECTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    CONFIRMED = "CONFIRMED"
    REJECTED = "REJECTED"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ReviewDecision(str, Enum):
    CONFIRM = "CONFIRM"
    REJECT = "REJECT"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    EDIT = "EDIT"


class AuditAction(str, Enum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    USER_CREATE = "USER_CREATE"
    PRODUCT_CREATE = "PRODUCT_CREATE"
    INSPECTION_CREATE = "INSPECTION_CREATE"
    INSPECTION_UPDATE = "INSPECTION_UPDATE"
    IMAGE_UPLOAD = "IMAGE_UPLOAD"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    VIOLATION_REVIEW = "VIOLATION_REVIEW"
    REPORT_GENERATED = "REPORT_GENERATED"
